version: '3'

services:
  backend:
    build: ./backend
    command: gunicorn --bind 0.0.0.0:8000 absconfig.wsgi:application
    volumes:
      - ./backend:/backend/
      - static_volume:/backend/staticfiles/
      - media_volume:/backend/mediafiles/
    env_file:
      - ./backend/.env
    expose:
      - 8000
    depends_on:
      - db


  db:
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_DB=dzencode_db
      - POSTGRES_USER=dzencode_user
      - POSTGRES_PASSWORD=dzencode_password
    volumes:
      - pg_data:/var/lib/postgresql/data/


  nginx:
    image: nginx:1.25.0-alpine
    depends_on:
      - backend
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_volume:/backend/staticfiles/
      - media_volume:/backend/mediafiles/

volumes:
  pg_data:
  static_volume:
  media_volume: