version: '3'

services:
  backend:
    build: ./backend
    command: gunicorn --bind 0.0.0.0:8000 absconfig.wsgi:application
    volumes:
      - ./backend:/server_backend/
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - database


  database:
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=$${POSTGRES_DB}
      - POSTGRES_USER=$${POSTGRES_USER}
      - POSTGRES_PASSWORD=$${POSTGRES_PASSWORD}
    env_file:
      - ./backend/.env
    volumes:
      - pg_data:/var/lib/postgresql/data/


#  nginx:
#    image: nginx:1.25.0-alpine
#    depends_on:
#      - backend
#    ports:
#      - "80:80"
#    volumes:
#      - ./nginx:/etc/nginx/conf.d

volumes:
  pg_data:

