version: '3'

services:
  backend:
    build: ./backend
    command: gunicorn --bind 0.0.0.0:8000 absconfig.wsgi:application
    volumes:
      - ./backend:/backend/
      - static_volume:/backend/staticfiles/
      - media_volume:/backend/mediafiles/
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    command: sh -c "npm install && npm start"
    volumes:
      - ./frontend:/frontend/
    expose:
      - 5173
    depends_on:
      - backend

  db:
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_DB=dzencode_db
      - POSTGRES_USER=dzencode_user
      - POSTGRES_PASSWORD=dzencode_password
    volumes:
      - pg_data:/var/lib/postgresql/data/

  nginx:
    image: nginx:1.25.0-alpine
    depends_on:
      - frontend
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_volume:/backend/staticfiles/
      - media_volume:/backend/mediafiles/

volumes:
  pg_data:
  static_volume:
  media_volume:
