# Generated by Django 4.2.2 on 2023-06-20 13:32

import comments.models_services
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=10000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(null=True, upload_to=comments.models_services.comment_file_path, validators=[comments.models_services.normal_item_image_size, comments.models_services.normal_image_format, comments.models_services.normal_width_and_height])),
                ('textfile', models.FileField(null=True, upload_to=comments.models_services.comment_file_path, validators=[comments.models_services.normal_textfile_size, comments.models_services.normal_textfile_format])),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
            ],
        ),
    ]
