# Generated by Django 4.2.2 on 2023-06-20 13:36

import comments.models_services
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(null=True, upload_to=comments.models_services.comment_file_path, validators=[comments.models_services.normal_item_image_size, comments.models_services.normal_image_format]),
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('owner', 'body', 'image', 'textfile')},
        ),
    ]
