# Generated by Django 4.2.2 on 2023-06-20 13:47

import comments.models_services
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0003_alter_comment_unique_together_alter_comment_image_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('owner', 'body')},
        ),
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=comments.models_services.comment_file_path, validators=[comments.models_services.normal_item_image_size, comments.models_services.normal_image_format]),
        ),
        migrations.AlterField(
            model_name='comment',
            name='textfile',
            field=models.FileField(blank=True, null=True, upload_to=comments.models_services.comment_file_path, validators=[comments.models_services.normal_textfile_size, comments.models_services.normal_textfile_format]),
        ),
    ]
